
function alemanha() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'block';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
};


function fecharalemanha() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function arabia() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'block';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
};

function fechararabia() {
    let modal = document.querySelector('.modal1')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function argentina() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'block';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
};

function fecharargentina() {
    let modal = document.querySelector('.modal2')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function belgica() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'block';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
};

function fecharbelgica() {
    let modal = document.querySelector('.modal3')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function brasil() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'block';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
};

function fecharbrasil() {
    let modal = document.querySelector('.modal4')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function camaroes() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'block';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
};

function fecharcamaroes() {
    let modal = document.querySelector('.modal5')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function canada() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'block';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
};

function fecharcanada() {
    let modal = document.querySelector('.modal6')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function catar() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'block';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
   
};

function fecharcatar() {
    let modal = document.querySelector('.modal7')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
  
}
function coreiadosul() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'block';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
   
};

function fecharcoreiadosul() {
    let modal = document.querySelector('.modal8')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
}
function croacia() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'block';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
   
};

function fecharcroacia() {
    let modal = document.querySelector('.modal9')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
    
}
function dinamarca() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'block';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
    
};

function fechardinamarca() {
    let modal = document.querySelector('.modal10')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
    
}
function espanha() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'block';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
    
};

function fecharespanha() {
    let modal = document.querySelector('.modal11')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
    
}
function eua() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'block';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
    
};

function fechareua() {
    let modal = document.querySelector('.modal12')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
   
}
function equador() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'block';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
    
};

function fecharequador() {
    let modal = document.querySelector('.modal13')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
    
}
function franca() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'block';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
    
};

function fecharfranca() {
    let modal = document.querySelector('.modal14')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
    
}
function gana() {
    let modal = document.querySelector('.modal')
    modal.style.display = 'none';
    let modal1 = document.querySelector('.modal1')
    modal1.style.display = 'none';
    let modal2 = document.querySelector('.modal2')
    modal2.style.display = 'none';
    let modal3 = document.querySelector('.modal3')
    modal3.style.display = 'none';
    let modal4 = document.querySelector('.modal4')
    modal4.style.display = 'none';
    let modal5 = document.querySelector('.modal5')
    modal5.style.display = 'none';
    let modal6 = document.querySelector('.modal6')
    modal6.style.display = 'none';
    let modal7 = document.querySelector('.modal7')
    modal7.style.display = 'none';
    let modal8 = document.querySelector('.modal8')
    modal8.style.display = 'none';
    let modal9 = document.querySelector('.modal9')
    modal9.style.display = 'none';
    let modal10 = document.querySelector('.modal10')
    modal10.style.display = 'none';
    let modal11 = document.querySelector('.modal11')
    modal11.style.display = 'none';
    let modal12 = document.querySelector('.modal12')
    modal12.style.display = 'none';
    let modal13 = document.querySelector('.modal13')
    modal13.style.display = 'none';
    let modal14 = document.querySelector('.modal14')
    modal14.style.display = 'none';
    let modal15 = document.querySelector('.modal15')
    modal15.style.display = 'block';
    let btn = document.querySelector('.btn')
    btn.style.display = 'none';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'none';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'none';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'none';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'none';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'none';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'none';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'none';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'none';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'none';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'none';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'none';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'none';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'none';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'none';
    let btn15 = document.querySelector('.btn15')
    btn15.style.display = 'none';
    
};

function fechargana() {
    let modal = document.querySelector('.modal15')
    modal.style.display = 'none';
    let btn = document.querySelector('.btn')
    btn.style.display = 'inline-flex';
    let btn1 = document.querySelector('.btn1')
    btn1.style.display = 'inline-flex';
    let btn2 = document.querySelector('.btn2')
    btn2.style.display = 'inline-flex';
    let btn3 = document.querySelector('.btn3')
    btn3.style.display = 'inline-flex';
    let btn4 = document.querySelector('.btn4')
    btn4.style.display = 'inline-flex';
    let btn5 = document.querySelector('.btn5')
    btn5.style.display = 'inline-flex';
    let btn6 = document.querySelector('.btn6')
    btn6.style.display = 'inline-flex';
    let btn7 = document.querySelector('.btn7')
    btn7.style.display = 'inline-flex';
    let btn8 = document.querySelector('.btn8')
    btn8.style.display = 'inline-flex';
    let btn9 = document.querySelector('.btn9')
    btn9.style.display = 'inline-flex';
    let btn10 = document.querySelector('.btn10')
    btn10.style.display = 'inline-flex';
    let btn11 = document.querySelector('.btn11')
    btn11.style.display = 'inline-flex';
    let btn12 = document.querySelector('.btn12')
    btn12.style.display = 'inline-flex';
    let btn13 = document.querySelector('.btn13')
    btn13.style.display = 'inline-flex';
    let btn14 = document.querySelector('.btn14')
    btn14.style.display = 'inline-flex';
    let btn15= document.querySelector('.btn15')
    btn15.style.display = 'inline-flex';
    
}